# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20170917_0406'),
        ('trade', '0004_add_canonical_goods'),
    ]

    operations = [
    ]
