# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_merge_20170917_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='need',
            name='value',
            field=models.IntegerField(),
        ),
    ]
