# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0006_auto_20170917_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='good',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='need',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
