# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0007_auto_20170917_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
