# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_auto_20170917_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
